---
# Reference: https://stackoverflow.com/questions/29075287/ansible-insert-line-if-not-exists

- name: Check whether the alias is exists or not
  shell: "grep -c -E '{{ alias.user }}:\\s+' {{ postfix_aliases_file }} || true"
  register: alias_result
  changed_when: not alias_result.stdout == '0'
  tags:
    - configuration
    - postfix
    - mail
    - postfix-configure-aliases
    - mail-configure-aliases
    - webserver

- debug:
    var: alias_result
  tags:
    - mail-configure-aliases

- name: Replace the alias because this alias already exists
  lineinfile:
    path: "{{ postfix_aliases_file }}"
    line: "{{ alias.user }}: {{ alias.alias }}"
    regexp: '^{{ alias.user | regex_escape }}:\s+'
    create: yes
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: not alias_result.stdout == '0'
  notify:
    - New aliases
    - Restart postfix
  tags:
    - configuration
    - postfix
    - mail
    - postfix-configure-aliases
    - mail-configure-aliases
    - webserver

- name: Insert a new alias because this alias does not exist
  lineinfile:
    path: "{{ postfix_aliases_file }}"
    line: "{{ alias.user }}: {{ alias.alias }}"
    insertafter: EOF
    create: yes
    owner: root
    group: root
    mode: 0644
  when: alias_result.stdout == '0'
  notify:
    - New aliases
    - Restart postfix
  tags:
    - configuration
    - postfix
    - mail
    - postfix-configure-aliases
    - mail-configure-aliases
    - webserver
